pks_plan_name: 'small'
pks_cluster_name: 'sample'
pks_cluster_master_node_hostname: "sample.prod.pks.sampledomain.com"
pks_cluster_number_of_workers: 3
pks_cluster_admin_ldap_group: 
- G_PCF_sample
- G_OperatorTeam
pks_cluster_readonly_ldap_group: []
