---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pks-kubectl

inputs:
- name: pks-onboarding-repo

run:
  path: pks-onboarding-repo/pks/ci/tasks/store-pks-cluster-kubeconfig-in-vault/task.sh

params:
  PCF_PKS_API:
  PKS_CLI_USER:
  PKS_CLI_PASSWORD:
  PKS_ENV:
  VAULT_URL:
  VAULT_ROLE_ID:
  VAULT_SECRET_ID:


