apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: CLUSTER_CERT_AUTH_DATA_ADMIN
    #insecure-skip-tls-verify: true
    server: CLUSTER_SERVER_ADMIN
  name: CLUSTER_NAME_ADMIN
contexts:
- context:
    cluster: CONTEXT_CLUSTER_ADMIN
    user: CONTEXT_USER
  name: CONTEXT_NAME_ADMIN
current-context: CONTEXT_CURRENT_ADMIN
kind: Config
preferences: {}
users:
- name: USER_NAME_USER
  user: 
    auth-provider:
      config:
        client-id: pks_cluster_client
        cluster_client_secret: ""
        id-token: USER_CONFIG_ID_TOKEN_USER
        idp-issuer-url: USER_CONFIG_IDP_ISSUER_URL_ADMIN
        refresh-token: USER_CONFIG_REFRESH_TOKEN_USER
      name: oidc