---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pks-kubectl

inputs:
- name: pks-onboarding-repo

run:
  path: pks-onboarding-repo/pks/ci/tasks/create-pks-cluster/task.sh

params:
  PCF_PKS_API:
  PKS_CLI_USER:
  PKS_CLI_PASSWORD:
  PKS_ENV:
